project:
  type: website

execute:
  freeze: true

website:
  title: "Guillaume's blog"
  site-url: https://castorfou.github.io
  description: "This is Guillaume Ramelet's personal blog."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/castorfou
      - icon: twitter
        href: https://twitter.com/GuillaumeRamel1
format:
  html:
    theme: cosmo
    css: styles.css
    from: markdown+autolink_bare_uris



