project:
  type: website

execute:
  freeze: true

website:
  title: "Guillaume's blog"
  favicon: favicon_small.png
  twitter-card: true
  google-analytics: "G-12YC1FPHWN"
  site-url: https://castorfou.github.io
  description: "This is Guillaume Ramelet's personal blog."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/castorfou
      - icon: twitter
        href: https://twitter.com/GuillaumeRamel1
format:
  html:
    theme: 
      light: journal
      dark: darkly
    css: styles.css
    from: markdown+autolink_bare_uris
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/castorfou\.github\.io\/**'    



