# AUTOGENERATED! DO NOT EDIT! File to edit: 2023-04-24-extract-python-scripts-with-nbdev.ipynb.

# %% auto 0
__all__ = ['nbdev_print']

# %% 2023-04-24-extract-python-scripts-with-nbdev.ipynb 21
def nbdev_print():
    print('This is a nbdev example')
