repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.3.13
  hooks:
  - id: nbdev_clean

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.12.0
  hooks:
  - id: black-jupyter

# - repo: https://github.com/astral-sh/ruff-pre-commit
#   # Ruff version.
#   rev: v0.1.8
#   hooks:
#     # Run the linter.
#     - id: ruff
#       types_or: [ python, pyi, jupyter ]
#       args: [ --fix ]
#     # Run the formatter.
#     - id: ruff-format
#       types_or: [ python, pyi, jupyter ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0 # Use the version you want
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=90000"]    
