repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.3.13
  hooks:
  - id: nbdev_clean

# Using this mirror lets us use mypyc-compiled black, which is about 2x faster
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.2.0
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.2.0
  hooks:
  - id: black-jupyter
    language_version: python3.10

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0 # Use the version you want
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=90000"]    
